### PR TITLE
[16.0][MIG] delivery_package_fee: Migrate to version 16.0

### PR DESCRIPTION
**Pull request by tuantrantg**
Note for the reviewer:
- The `price` field (of `product.product` model) in 14.0 is replaced by the `_get_contextual_price` function (of model `product.product`) in 16.0. You can see the details in [here](https://github.com/odoo/odoo/commit/9e99a9df464d97a74ca320d200599f7dce2d3050)

### CODE REVIEW

**Comment by dzungtran89** [comment]
@tuantrantg could you please seperate the prettier commit from the migration commit? See [here](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch)

**Comment by nilshamerlinck** [comment]
and please also remove `[16.0]` prefix in migration commit (but not in final PR title)

**Comment by tuantrantg** [comment]
> @tuantrantg could you please seperate the prettier commit from the migration commit? See [here](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch)

anh @dzungtran89 please review again

**Review by dzungtran89 — APPROVED** [review]
lgtm

**Pull request closed without merging**
